name: geopandas-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas>=0.11
  - dask-geopandas>=0.1.3
  - pyogrio
  - pyarrow
  - python-graphviz
  - esda
  - dask-labextension
  - awscli
  - boto3
  - ipykernel


